#!/usr/bin/env bash
#
# Generates /etc/nginx/conf.d/cloudflare-realip.conf from Cloudflare's published
# IP ranges, so nginx rewrites REMOTE_ADDR to the real visitor address.
#
# Why nginx rather than Laravel's TrustProxies:
#   nginx corrects the address before PHP ever runs, so $request->ip(), the rate
#   limiter, the audit log and anything else reading the client IP are all
#   correct with no application change. TrustProxies only fixes what Laravel
#   sees, and has to be kept in step with Cloudflare's ranges by hand.
#
# WITHOUT THIS, every request behind Cloudflare arrives from a Cloudflare
# address. The 120 requests/minute per-IP limiter would then see all traffic as
# one client and lock out the entire user base within seconds.
#
# Run BEFORE switching DNS to Cloudflare. Harmless while DNS is still direct:
# nginx only trusts these headers from the listed ranges, and no traffic comes
# from them yet.
#
#   sudo bash deploy/nginx/cloudflare-realip.sh

set -euo pipefail

OUT=/etc/nginx/conf.d/cloudflare-realip.conf
TMP=$(mktemp)

[[ $EUID -eq 0 ]] || { echo "run with sudo" >&2; exit 1; }

if ! nginx -V 2>&1 | grep -q -- '--with-http_realip_module\|http_realip'; then
    echo "WARNING: nginx may lack ngx_http_realip_module; check 'nginx -V'" >&2
fi

echo "fetching Cloudflare ranges..."
v4=$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v4)
v6=$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v6)

# A truncated or empty download would silently produce a config that trusts
# nothing — or worse, a partial list that breaks some visitors and not others.
[[ $(grep -c . <<<"$v4") -ge 10 ]] || { echo "IPv4 list looks wrong, aborting" >&2; exit 1; }
[[ $(grep -c . <<<"$v6") -ge 5  ]] || { echo "IPv6 list looks wrong, aborting" >&2; exit 1; }

{
    echo "# Generated by deploy/nginx/cloudflare-realip.sh on $(date -u +%F)"
    echo "# Source: https://www.cloudflare.com/ips-v4 and /ips-v6"
    echo "# Re-run after Cloudflare changes its ranges."
    echo
    while read -r cidr; do [[ -n $cidr ]] && echo "set_real_ip_from $cidr;"; done <<<"$v4"
    while read -r cidr; do [[ -n $cidr ]] && echo "set_real_ip_from $cidr;"; done <<<"$v6"
    echo
    echo "# CF-Connecting-IP carries the original visitor address and, unlike"
    echo "# X-Forwarded-For, is a single value Cloudflare always overwrites —"
    echo "# a client cannot prepend a forged entry to it."
    echo "real_ip_header CF-Connecting-IP;"
    echo "real_ip_recursive on;"
} > "$TMP"

install -m 0644 "$TMP" "$OUT"
rm -f "$TMP"
echo "wrote $OUT ($(grep -c set_real_ip_from "$OUT") ranges)"

if nginx -t; then
    systemctl reload nginx
    echo "reloaded."
else
    echo "nginx rejected the config — removing $OUT" >&2
    rm -f "$OUT"
    nginx -t
    exit 1
fi
